<!DOCTYPE html>
<html lang="fr">
<head>

	<meta charset="utf-8">
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<meta name="robots" content="all">

	<title><?php echo $this->title . ' - ' . $this->subtitle; ?></title>
	<meta name="keywords" content="dewep">
	<meta name="description" content="Claé - Les Courlis - Villers-Lès-Luxeuil">
	<meta name="author" content="dewep, aurelien, maigret, ink, cookbook, recipes">

	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<!--<link rel="shortcut icon" href="../img/ink-favicon.ico">-->

	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('static/ink-2.2.0/css/ink.css'); ?>">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<!--[if IE 7 ]>
	<link rel="stylesheet" href="<?php echo $this->baseUrl('static/ink-2.2.0/css/ink-ie7.css'); ?>" type="text/css" media="screen" title="no title" charset="utf-8">
	<![endif]-->

	<script type="text/javascript" src="<?php echo $this->baseUrl('static/ink-2.2.0/js/holder.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('static/ink-2.2.0/js/ink.min.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('static/ink-2.2.0/js/ink-ui.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('static/jquery/jquery-1.10.2.min.js'); ?>"></script>
	<!--<script type="text/javascript" src="<?php echo $this->baseUrl('static/ink-2.2.0/js/autoload.js'); ?>"></script>-->
	<script type="text/javascript" src="<?php echo $this->baseUrl('static/ink-2.2.0/js/html5shiv.js'); ?>"></script>

	<style type="text/css">
		body {
			background: #ededed;
			background: #F0F0F0;
			font-size: 14px;
		}
		header {
			/*padding: 2em 0 1em;
			margin-bottom: 0.5em;*/
		}
		#header {
			border-bottom: 1px solid #CCC;
			background: #DFDFDF;
			padding: 2em 0 1em;
			margin: 0 0 1em;
			font-size: 1.1em;
		}
		h1 {
			font-size: 2em;
		}
		h1 small:before {
			content: "|";
			margin: 0 0.5em;
			font-size: 1.6em;
		}
		footer {
			color: #333;
			border-top: 1px solid #ccc;
			background: #DFDFDF;
		}
		footer p {
			padding: 0.5em 1em 0.5em 0;
			margin: 0;
		}
		table.ink-table.alternating tbody tr:nth-child(odd) {
			background-color: #fff;
		}
		header nav + nav {
			margin: 0 10px 0 0;
		}
		nav li.label {
			padding: 0.5em 1em;
			display: inline-block;
			color: #AAA;
		}
		header nav li.separator-left {
			padding-left: 1em;
			margin-left: 1em;
			border-left: 1px solid #EEE;
		}
		header nav li.separator-left.label {
			padding-left: 2em;
		}
		.ink-alert.basic, .ink-alert.block h4 {
			padding: 0.5em 1em;
		}
		.ink-button.button-small {
			padding: 2px 5px;
			font-weight: normal;
			font-size: 13px;
		}
		.ink-tabs .tabs-content {
			overflow: hidden;
		}
	</style>
</head>

<body>

	<?php if (User::isLogas()): ?>
		<nav class="ink-navigation">
			<ul class="menu horizontal orange">
				<li>
					<span class="left-space">
						Vous êtes connecté de force avec le compte de <?php echo User::getString(); ?>.
						<a href="<?php echo $this->baseUrl('User/Session/Deconnexion'); ?>" class="left-space">Déconnexion</a>
					</span>
				</li>
			</ul>
		</nav>
	<?php endif; ?>

	<div id="header">
		<div class="ink-grid">
			<?php $this->render('header'); ?>
		</div>
	</div>

	<div class="ink-grid">

		<?php if (isset($this->alert)): ?>

			<div class="ink-alert block <?php echo $this->alert->type; ?>">
				<!--<button class="ink-dismiss">&times;</button>-->
				<h4><?php echo $this->alert->title; ?></h4>
				<p><?php echo $this->alert->content; ?></p>
			</div>

		<?php endif; ?>

		<?php if (!isset($this->alert) || !$this->alert->force): ?>

			<!--<div class="ink-alert basic"><p><b>Attention:</b> La sortie dans les bois du 15 juillet est annulée ; trop peu d'enfants étaient inscrits.</p></div>-->
			<?php $this->renderAction(); ?>

		<?php endif; ?>

	</div>

	<?php $this->render('footer'); ?>

</body>
</html>
