<footer>
	<div class="ink-grid">
		<nav class="ink-navigation push-left medium-100 small-100 small-push-left">
			<ul class="menu horizontal">
				<li class=""active><a href="<?php echo $this->baseUrl('/'); ?>">Accueil</a></li>
				<li><a href="<?php echo $this->baseUrl('/Default/MentionsLegales'); ?>">Mentions légales</a></li>
				<li><a href="<?php echo $this->baseUrl('/Default/Aide'); ?>">Aide</a></li>
			</ul>
		</nav>
		<p class="push-right small-100"><a href="http://www.dewep.net" class="small">Réalisation Dewep.net</a></p>
	</div>
</footer>
