<header>
	<div class="column-group">
		<nav class="ink-navigation hide-small">
			<ul class="menu horizontal black rounded shadowed">
				<li class="activee" style="margin-left: 1em;"><a href="/"><i class="icon-home"></i></a></li>
				<li class="label separator-left">École <i class="icon-double-angle-right"></i></li>
				<li><a href="/Blog">Blog</a></li>
				<li class="label separator-left">Claé <i class="icon-double-angle-right"></i></li>
				<li><a href="/Activites">Activités</a></li>
				<li><a href="/Configuration">Configuration</a></li>
				<li><a href="/Inscription">Inscription</a></li>
				<li class="separator-left"><a href="/Connexion">Connexion</a></li>
				<li class="separator-left"><a href="/Deconnexion">Déconnexion</a></li>
			</ul>
		</nav>
	</div>
	<br>
	<!--<div class="column-group">
		<nav class="ink-navigation pull-right medium-100 small-100">
			<ul class="menu horizontal black shadowed">
				<li><a href="#">Connexion</a></li>
				<li><a href="#">Déconnexion</a></li>
			</ul>
		</nav>
		<nav class="ink-navigation pull-right medium-100 small-100">
			<ul class="menu horizontal black shadowed">
				<li class="label">Claé <i class="icon-double-angle-right"></i></li>
				<li><a href="#">Activités</a></li>
				<li><a href="#">Configuration</a></li>
				<li><a href="#">Inscription</a></li>
			</ul>
		</nav>
		<nav class="ink-navigation pull-right medium-100 small-100">
			<ul class="menu horizontal black shadowed">
				<li class="label">École <i class="icon-double-angle-right"></i></li>
				<li><a href="#">Blog</a></li>
			</ul>
		</nav>
		<nav class="ink-navigation pull-right medium-100 small-100">
			<ul class="menu horizontal black shadowed">
				<li><a href="#">Accueil</a></li>
			</ul>
		</nav>
	</div>-->
	<div class="column-group">
		<h1 class="pull-left medium-100 small-100">Les Courlis <small>Villers-Lès-Luxeuil</small></h1>
	</div>
</header>

<!--<header>
	<div class="column-group">
		<div class="medium-100 small-100">
			<h1 class="pull-left medium-100 small-100">Les Courlis <small>Villers-Lès-Luxeuil</small></h1>
		</div>
	</div>
	<div class="column-group">
	<div class="medium-100 small-100">
	<nav class="ink-navigation pull-right medium-100 small-100">
		<ul class="menu horizontal black shadowed">
			<li><a href="#">Connexion</a></li>
		</ul>
	</nav>
	<nav class="ink-navigation pull-right medium-100 small-100">
		<ul class="menu horizontal black shadowed">
			<li class="label">Claé <i class="icon-double-angle-right"></i></li>
			<li><a href="#">Infos rapides</a></li>
			<li><a href="#">Activités</a></li>
			<li><a href="#">Configuration</a></li>
		</ul>
	</nav>
	<nav class="ink-navigation pull-right medium-100 small-100">
		<ul class="menu horizontal black shadowed">
			<li class="label">École <i class="icon-double-angle-right"></i></li>
			<li><a href="#">Blog</a></li>
		</ul>-->
		<!--<ul class="menu horizontal black shadowed">
			<li class="active"><a href="index.html">Accueil</a></li>
			<li><a href="#">École <i class="icon-caret-down"></i></a>
				<ul class="submenu">
					<li><a href="#">Blog</a></li>
					<li><a href="#">Albums photos</a></li>
				</ul>
			</li>
			<li><a href="#">Claé <i class="icon-caret-down"></i></a>
				<ul class="submenu">
					<li><a href="#">Infos rapides</a></li>
					<li><a href="#">Activités</a></li>
					<li><a href="#">Configuration</a></li>
				</ul>
			</li>
			<li><a href="aide.html">Contact</a></li>
			<li><a href="aide.html">Aide</a></li>
		</ul>-->
		<!--<ul class="menu horizontal black shadowed">
			<li class="active"><a href="index.html">Accueil</a></li>
			<li><a href="#">Item with a submenu</a>
				<ul class="submenu">
					<li><a href="#">Subitem 1</a></li>
					<li><a href="#">Subitem 2</a></li>
				</ul>
			</li>
			<li><a href="activites.html">Claé</a></li>
			<li><a href="activites.html">Activités du claé</a></li>
			<li><a href="configurations.html">Configuration</a></li>
			<li><a href="aide.html">Aide</a></li>
		</ul>-->
	<!--</nav>
	</div>
	</div>
</header>-->
