<header>
	<div class="column-group">
		<nav class="ink-navigation hide-small">
			<ul class="menu horizontal black rounded shadowed">
				<li class="activee" style="margin-left: 1em;"><a href="<?php echo $this->baseUrl('/'); ?>"><i class="icon-home"></i></a></li>
				<li class="label separator-left">École <i class="icon-double-angle-right"></i></li>
				<li><a href="<?php echo $this->baseUrl('/Blog'); ?>">Blog</a></li>
				<li class="label separator-left">Claé <i class="icon-double-angle-right"></i></li>
				<li><a href="<?php echo $this->baseUrl('/Activites'); ?>">Activités</a></li>
				<li><a href="<?php echo $this->baseUrl('/Configuration'); ?>">Configuration</a></li>
				<li><a href="<?php echo $this->baseUrl('/Inscription'); ?>">Inscription</a></li>
				<li class="separator-left"><a href="<?php echo $this->baseUrl('/Connexion'); ?>">Connexion</a></li>
				<li class="separator-left"><a href="<?php echo $this->baseUrl('/Deconnexion'); ?>">Déconnexion</a></li>
			</ul>
		</nav>
	</div>
	<br>
	<div class="column-group">
		<h1 class="pull-left medium-100 small-100">Les Courlis <small>Villers-Lès-Luxeuil</small></h1>
	</div>
</header>
