<div class="column-group gutters">
	<div class="large-100 medium-100 small-100">
		<h3>Gestions des utilisateurs</h3>
		<div class="ink-tabs left" id="manage_users">
			<ul class="tabs-nav">
				<li><a href="#confirm">À confirmer (<?php echo count($this->users['confirm']); ?>)</a></li>
				<li><a href="#parents">Comptes parents (<?php echo count($this->users['parents']); ?>)</a></li>
				<li><a href="#admin">Comptes admins (<?php echo count($this->users['admin']); ?>)</a></li>
			</ul>
			<div id="confirm" class="tabs-content">
				<table class="ink-table alternating bordered content-center half-top-space" data-page-size="10">
					<thead>
						<tr>
							<th data-sortable="true" width="33%">Nom</th>
							<th data-sortable="true" width="33%">Prénom</th>
							<th data-sortable="true" width="34%">Actions</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($this->users['confirm'] as $user): ?>
							<tr>
								<td><?php echo $user->name; ?></td>
								<td><?php echo $user->firstname; ?></td>
								<td>
									<form method="post">
										<input type="hidden" name="token" value="<?php echo Dewep_CSRF::get(); ?>">
										<input type="hidden" name="user_id" value="<?php echo $user->id; ?>">
										<input type="submit" name="logas" class="ink-button button-small blue" value="Logas">
										<input type="submit" name="confirm" class="ink-button button-small green" value="Confirmer">
									</form>
								</td>
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
				<nav class="ink-navigation" id="nav_confirm"><ul class="pagination"></ul></nav>
			</div>
			<div id="parents" class="tabs-content">
				<table class="ink-table alternating bordered content-center half-top-space" data-page-size="10">
					<thead>
						<tr>
							<th data-sortable="true" width="33%">Nom</th>
							<th data-sortable="true" width="33%">Prénom</th>
							<th data-sortable="true" width="34%">Actions</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($this->users['parents'] as $user): ?>
							<tr>
								<td><?php echo $user->name; ?></td>
								<td><?php echo $user->firstname; ?></td>
								<td>
									<form method="post">
										<input type="hidden" name="token" value="<?php echo Dewep_CSRF::get(); ?>">
										<input type="hidden" name="user_id" value="<?php echo $user->id; ?>">
										<input type="submit" name="logas" class="ink-button button-small blue" value="Logas">
										<input type="button" name="edit_user" class="ink-button button-small blue" value="Éditer">
										<input type="submit" name="delete_user" class="ink-button button-small red" value="Supprimer">
									</form>
								</td>
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
				<nav class="ink-navigation" id="nav_users"><ul class="pagination"></ul></nav>
			</div>
			<div id="admin" class="tabs-content">
				<table class="ink-table alternating bordered content-center half-top-space" data-page-size="10">
					<thead>
						<tr>
							<th data-sortable="true" width="33%">Nom</th>
							<th data-sortable="true" width="33%">Prénom</th>
							<th data-sortable="true" width="34%">Actions</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($this->users['admin'] as $user): ?>
							<tr>
								<td><?php echo $user->name; ?></td>
								<td><?php echo $user->firstname; ?></td>
								<td>
									<form method="post">
										<input type="hidden" name="token" value="<?php echo Dewep_CSRF::get(); ?>">
										<input type="hidden" name="user_id" value="<?php echo $user->id; ?>">
										<input type="button" name="edit_user" class="ink-button button-small blue" value="Éditer">
										<input type="submit" name="delete_user" class="ink-button button-small red" value="Supprimer">
									</form>
								</td>
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
				<nav class="ink-navigation" id="nav_admin"><ul class="pagination"></ul></nav>
			</div>
			<div class="popup"></div>
		</div>
		<script type="text/javascript">
		$(function(){
			var tabs = new Ink.UI.Tabs('#manage_users', {
				active: '#confirm',
				onBeforeChange: function(tab){
					/*console.log('beforeChange', tab);*/
				},
				onChange: function(tab){
					/*console.log('Changed', tab);*/
				}
			});
			var table_confirm = new Ink.UI.Table('#confirm .ink-table', {
				pagination: '#nav_confirm'
			});
			var table_users = new Ink.UI.Table('#parents .ink-table', {
				pagination: '#nav_users'
			});
			var table_admin = new Ink.UI.Table('#admin .ink-table', {
				pagination: '#nav_admin'
			});
			$('#manage_users input[type=submit][name=delete_user]').click(function(event) {
				if ($(this).attr('confirm_delte'))
					return true;
				$(this).attr('confirm_delte', 'true');
				popup_info('Confirmer la suppression', 'Attention cette action est supprimera l\'utilisateur. Si vous êtes sûr, recliquer une nouvelle fois sur le bouton.');
				return false;
			});
			$('#manage_users input[type=button][name=edit_user]').click(function(event) {
				var id_user = $(this).parent().find('input[name=user_id]').val();
				var token = $(this).parent().find('input[name=token]').val();
				$('#manage_users .popup').popup(
					'Éditer un utilisateur',
					'<div class="waiter">Chargement en cours</div>',
					[{
						pos: 'left',
						className: 'red',
						content:'Annuler',
						onclick: function(ink, params){
							ink.dismiss();
						},
						'params': null
					},
					{
						pos: 'right',
						className: 'green',
						content: 'Enregistrer',
						onclick: function(ink, params){
							if ($('#manage_users .popup .content form'))
							{
								var content = $('#manage_users .popup .content');
								var checkbox = {};
								content.find(':checkbox').each(function(index, el) {
									checkbox[$(this).attr('name')] = ($(this).is(':checked')) ? true : false;
								});
								$.ajax({
								url: baseUrl('User/Administration/setUser?format=json'),
								type: 'POST',
								dataType: 'json',
								data: {
									id: id_user,
									token: token,
									name: content.find('input[name=name]').val(),
									firstname: content.find('input[name=firstname]').val(),
									mail: content.find('input[name=mail]').val(),
									rights: checkbox
								},
								success: function(json)
								{
									var content = $('#manage_users .popup .content');
									$('#manage_users input[name=user_id][value=' + id_user + ']').each(function(index, el) {
										var tr = $(this).parents('tr:first');
										tr.find('td:nth(0)').text(content.find('input[name=name]').val());
										tr.find('td:nth(1)').text(content.find('input[name=firstname]').val());
									});
									ink.dismiss();
									popup_success(json.success, json.details);
								},
								error: function(json) {
									json = json.responseJSON;
									popup_error(json.error, json.details);
								}
							});
							}
							else
								ink.dismiss();
						},
						'params': null
					}],
					[{name:'width', value:'500px'}]
				);
				$.ajax({
					url: baseUrl('User/Administration/getUser?format=json'),
					type: 'POST',
					dataType: 'json',
					data: {id: id_user, token: token},
					success: function(json)
					{
						var content = $('#manage_users .popup .content');
						var template = '' +
							'<form action="' + baseUrl('User/Administration/setUser?format=json') + '" method="post" class="ink-form">' +
								'<fieldset>' +
									'<div class="control-group column-group gutters">' +
										'<label class="large-30 content-right" for="edit_user_name">Nom :</label>' +
										'<div class="control large-70">' +
											'<input type="text" name="name" id="edit_user_name">' +
										'</div>' +
										'<label class="large-30 content-right" for="edit_user_firstname">Prénom :</label>' +
										'<div class="control large-70">' +
											'<input type="text" name="firstname" id="edit_user_firstname">' +
										'</div>' +
										'<label class="large-30 content-right" for="edit_user_mail">E-Mail :</label>' +
										'<div class="control large-70">' +
											'<input type="text" name="mail" id="edit_user_mail">' +
										'</div>' +
										'<label class="large-30 content-right rights">Permissions :</label>' +
										'<div class="control large-70 rights">' +
										'</div>' +
									'</div>' +
								'</fieldset>' +
							'</form>';
						content.html(template);
						content.find('input[name=name]').val(json.name);
						content.find('input[name=firstname]').val(json.firstname);
						content.find('input[name=mail]').val(json.mail);
						if (json.type == 'admin')
						{
							console.log(json);
							for (var right in json.rights) {
								content.find('div.rights').append('' +
										'<input type="checkbox" name="' + right + '" value="true" id="right_' + right + '"' + (json.rights[right] ? ' checked' : '') + '>' +
										' <label for="right_' + right + '">' + json.rights_definitions[right] + '</label>'
									);
							};
						}
						else
							content.find('.rights').hide();
						$('#manage_users .popup .ink-modal').data('ink')._onResize(true);
					},
					error: function(json) {
						json = json.responseJSON;
						popup_error(json.error, json.details);
					}
				});
			});
		});
		</script>
	</div>
</div>
