<div class="column-group">
	<div class="large-100 medium-100 small-100">
		<div class="ink-alert basic"><p><b>Attention:</b> La sortie dans les bois du 15 juillet est annulée ; trop peu d'enfants étaient inscrits.</p></div>
		<h3>Vos prochaines inscriptions</h3>
		<table class="ink-table alternating bordered">
			<thead>
				<tr>
					<th>Date</th>
					<th>Activité</th>
					<th>Enfants</th>
					<th>Prix total</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Mardi 6 juillet</td>
					<td>Sortie Zoo</td>
					<td>Dupond Florent</td>
					<td>28 <i class="icon-euro"></i></td>
				</tr>
				<tr>
					<td>Vendredi 3 septembre</td>
					<td>Promenade bois</td>
					<td>Dupond Florent</td>
					<td>Gratuit</td>
				</tr>
				<tr>
					<td>Samedi 14 septembre</td>
					<td>Danse</td>
					<td>Dupond Fiora</td>
					<td>Gratuit</td>
				</tr>
				<tr>
					<td>Lundi 20 octobre</td>
					<td>Repas le midi</td>
					<td>Dupond Florent<br>Dupond Fiora</td>
					<td>14 <i class="icon-euro"></i></td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<br><br>
<div class="column-group gutters">
	<div class="large-60 medium-50 small-100">
		<h3>News</h3>
		<p>Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news.</p><hr>
		<p>Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news.</p><hr>
		<p>Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news. Une news.</p><hr>
		<p>Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news. Une autre news.</p>
	</div>
	<div class="large-40 medium-50 small-100">
		<h3>Les repas</h3>
		<img src="holder.js/550x200/auto/ink" alt="">
		<h4 class="content-center"><i class="icon-arrow-left"></i> Lundi 3 septembre <i class="icon-arrow-right"></i></h4>
		<p class="content-center">Salade verte<br>Steak haché<br>Haricots verts<br>Glace</p>
	</div>
</div>
