<div class="ink-alert basic">
	<p>
		<b>Pour tester le site ( le mot de passe est le même que le login ) :</b><br>
		<u>Compte admin :</u> admin <br>
		<u>Compte admin :</u> admin2<br>
		<u>Compte parent 1 :</u> parent<br>
		<u>Compte parent 2 :</u> parent2<br>
	</p>
</div>

<h2>Listes des mises à jour</h2>

<h4>Vendredi 13 septembre</h4>
<ul>
	<li>Pouvoir éditer un utilisateur (reste l'enregistrement)</li>
</ul>

<h4>Mardi 10 septembre</h4>
<ul>
	<li>Pouvoir confirmer un compte en tant qu'admin</li>
	<li>Pouvoir se logas sur un compte parent</li>
</ul>

<h4>Lundi 9 septembre</h4>
<ul>
	<li>Page d'administration de base</li>
</ul>

<h4>Mardi 3 septembre</h4>
<ul>
	<li>Amélioration page de préférences.</li>
</ul>

<h4>Lundi 2 septembre</h4>
<ul>
	<li>Page de préférences (éditer ses infos, et gérer la liste de ses enfants). Mais pas vraiment securise pour le moment.</li>
</ul>

<h4>Dimanche 1er septembre</h4>
<ul>
	<li>Créations des pages principales (mais vides)</li>
	<li>Pouvoir se Connecter / Déconnecter</li>
	<li>Proposition affichage de la garderie</li>
</ul>
